import PDFDocument from 'pdfkit';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import multer from 'multer';
import pool from '../config/db.js';
import { TIMETABLE_DIR, UPLOAD_DIR } from '../config/storage.js';
import { q, one, exec, sqlDate, startOfToday, asDate, fmtDate, fmtTime, pct1, ATTENDANCE_THRESHOLD } from '../utils/dbHelpers.js';
import { awardBadges, POINTS_LATE, POINTS_ON_TIME, recomputeAttendance, recomputeClassAttendance } from './attendanceController.js';
import { sendEmail, emailTemplates, emailSettings, isEmailConfigured, missingEmailSettings, describeEmailError } from '../config/email.js';
import { allow } from '../utils/rateLimit.js';

const T = ATTENDANCE_THRESHOLD;
const HOURS = (h) => new Date(Date.now() + h * 3600 * 1000);
const DAY_ORDER = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];

// Wrap every handler so a thrown error becomes a clean JSON 500 (details only in the server log)
export const wrap = (fn) => async (req, res) => {
  try { await fn(req, res); } catch (err) { console.error(`${req.method} ${req.originalUrl} failed:`, err); res.status(500).json({ error: 'Something went wrong on the server.' }); }
};
const bad = (res, msg, code = 400) => res.status(code).json({ error: msg });

// ---------- timetable files: ANY file type up to 10 MB, stored privately ----------
// Files live in backend/storage/timetables (NOT in the publicly served /uploads folder) and are only handed out by
// sendTimetableFile() to signed-in users who may see them. Only PDF and common image types open in the browser;
// everything else (including HTML/SVG, which can run scripts) is forced to download, with nosniff.
export const MAX_TIMETABLE_BYTES = 10 * 1024 * 1024;
const PREVIEW_TYPES = { pdf: 'application/pdf', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', webp: 'image/webp' };
const PREVIEWABLE = new Set(Object.values(PREVIEW_TYPES));
const safeExt = (name) => path.extname(String(name || '')).slice(1).toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 10);
const cleanName = (name) => path.basename(String(name || 'timetable').replace(/\\/g, '/')).replace(/[\u0000-\u001f"]/g, '').trim().slice(0, 200) || 'timetable';
const fileInfo = (v) => (v.file_path ? { name: v.file_name, type: v.file_type, size: v.file_size, previewable: PREVIEWABLE.has(v.file_type) } : null);

export const timetableUpload = multer({
  storage: multer.diskStorage({
    destination: (req, file, cb) => { fs.mkdirSync(TIMETABLE_DIR, { recursive: true }); cb(null, TIMETABLE_DIR); },
    // the stored name is generated by the server, so a hostile original filename can never choose where the file goes
    filename: (req, file, cb) => { const ext = safeExt(file.originalname); cb(null, `${crypto.randomUUID()}${ext ? `.${ext}` : ''}`); },
  }),
  limits: { fileSize: MAX_TIMETABLE_BYTES, files: 1 },
});

// GET .../:id/file  (rep: own class only; HOD/admin: any)   ?download=1 forces a download
export const sendTimetableFile = wrap(async (req, res) => {
  const v = await one('SELECT * FROM timetable_versions WHERE id = ?', [req.params.id]);
  if (!v || !v.file_path) return bad(res, 'This timetable has no file attached.', 404);
  if (['student', 'student_rep'].includes(req.user.role) && v.class_code !== req.user.class_code) return bad(res, "That isn't your class's timetable.", 403);
  if (req.user.role === 'student' && v.status !== 'approved') return bad(res, 'Students can only view approved timetables.', 403);
  const full = path.join(TIMETABLE_DIR, path.basename(v.file_path));
  if (!fs.existsSync(full)) return bad(res, 'The stored file is missing from the server.', 404);

  const inline = !req.query.download && PREVIEWABLE.has(v.file_type);
  const ascii = v.file_name.replace(/[^\x20-\x7e]/g, '_');
  res.setHeader('Content-Type', inline ? v.file_type : 'application/octet-stream');
  res.setHeader('Content-Disposition', `${inline ? 'inline' : 'attachment'}; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(v.file_name)}`);
  res.setHeader('Content-Length', fs.statSync(full).size);
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Cache-Control', 'private, no-store');
  fs.createReadStream(full).pipe(res);
});


const classOf = (req) => (req.user.role === 'admin' ? req.query.class_code || req.body?.class_code || req.user.class_code : req.user.class_code);
const me = (req) => one('SELECT s.*, u.name, u.email, u.class_code FROM students s JOIN users u ON u.id = s.user_id WHERE s.user_id = ?', [req.user.id]);
const classStudents = (cc) => q(
  `SELECT s.adm_no, s.points, s.attendance_pct, s.parent_email, s.parent_phone, u.id AS user_id, u.name, u.email, u.role
   FROM students s JOIN users u ON u.id = s.user_id WHERE u.class_code = ? AND u.status = 'active' ORDER BY u.name`, [cc]);
const sessionsHeld = async (cc) => (await one('SELECT COUNT(*) AS n FROM sessions WHERE class_code = ?', [cc])).n;

async function admOf(req) {
  if (req.user.adm_no) return req.user.adm_no;
  return (await one('SELECT adm_no FROM students WHERE user_id = ?', [req.user.id]))?.adm_no || null;
}

// ---------- shared PDF / CSV output ----------
function sendPdf(res, filename, title, subtitle, headers, rows, widths) {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);
  doc.font('Helvetica-Bold').fontSize(15).text(title);
  doc.font('Helvetica').fontSize(9).fillColor('#555555').text(subtitle).moveDown();
  let y = doc.y;
  const row = (cells, bold) => {
    let x = 40;
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor('#000000');
    cells.forEach((c, i) => { doc.text(String(c ?? ''), x, y, { width: widths[i] - 4, lineBreak: false, ellipsis: true }); x += widths[i]; });
    y += 16;
  };
  row(headers, true);
  rows.forEach((r) => { if (y > 780) { doc.addPage(); y = 40; } row(r, false); });
  if (!rows.length) { doc.text('No records.', 40, y); }
  doc.end();
}
const csvCell = (v) => `"${String(v ?? '').replace(/"/g, '""')}"`;
const sendCsv = (res, filename, headers, rows) => {
  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.send([headers, ...rows].map((r) => r.map(csvCell).join(',')).join('\n'));
};

const chatTimestamp = (value) => {
  const raw = value instanceof Date ? value.toISOString() : String(value || '');
  const normalized = /(?:Z|[+-]\d{2}:?\d{2})$/i.test(raw) ? raw : `${raw.replace(' ', 'T')}Z`;
  const timestamp = new Date(normalized);
  return Number.isNaN(timestamp.getTime()) ? null : timestamp.toISOString();
};
const announcementOut = (m) => ({
  id: m.id, text: m.message, timestamp: chatTimestamp(m.created_at),
  time: fmtTime(m.created_at), date: fmtDate(m.created_at),
  sender: m.name, sender_id: m.sender_id, announcement: !!m.is_announcement,
});

async function postChat(req, res, announcement) {
  const message = String(req.body.message || '').trim();
  if (!message) return bad(res, 'Message cannot be empty.');
  const cc = classOf(req);
  if (!cc) return bad(res, 'Your account has no class.');
  const r = await exec('INSERT INTO chat_messages (class_code, sender_id, message, is_announcement) VALUES (?, ?, ?, ?)', [cc, req.user.id, message, announcement ? 1 : 0]);
  const row = await one('SELECT m.*, u.name FROM chat_messages m JOIN users u ON u.id = m.sender_id WHERE m.id = ?', [r.insertId]);
  const out = announcementOut(row);
  req.app.get('io')?.to(cc).emit('receive_message', { ...out, class_code: cc });
  res.status(201).json({ ...out, mine: true });
}

// =========================================================================================
// STUDENT
// =========================================================================================
export const student = {
  timetable: wrap(async (req, res) => {
    const v = await one("SELECT * FROM timetable_versions WHERE class_code = ? AND status = 'approved' ORDER BY id DESC LIMIT 1", [req.user.class_code]);
    if (!v) return res.json({ version: null, slots: [] });
    const slots = await q('SELECT * FROM timetable_slots WHERE version_id = ?', [v.id]);
    slots.sort((a, b) => DAY_ORDER.indexOf(a.day_of_week.toLowerCase()) - DAY_ORDER.indexOf(b.day_of_week.toLowerCase()) || String(a.start_time).localeCompare(String(b.start_time)));
    res.json({
      version: { id: v.id, term: v.term, status: v.status, comment: v.hod_comment, uploaded: fmtDate(v.created_at), file: fileInfo(v) },
      slots: slots.map((s) => ({ id: s.id, day: s.day_of_week, time: `${String(s.start_time).slice(0, 5)} - ${String(s.end_time).slice(0, 5)}`, unit: s.unit_name, venue: s.venue, lecturer: s.lecturer_name })),
    });
  }),
  dashboard: wrap(async (req, res) => {
    const st = await me(req);
    if (!st) return bad(res, 'No student record is linked to this account.', 404);
    const board = await q('SELECT s.adm_no FROM students s JOIN users u ON u.id = s.user_id WHERE u.class_code = ? AND u.status = ? ORDER BY s.points DESC, s.adm_no ASC', [st.class_code, 'active']);
    const rank = board.findIndex((b) => b.adm_no === st.adm_no) + 1;
    const recent = await q(
      'SELECT l.id AS log_id FROM sessions s LEFT JOIN attendance_logs l ON l.session_id = s.id AND l.adm_no = ? WHERE s.class_code = ? ORDER BY s.start_time DESC, s.id DESC LIMIT 30',
      [st.adm_no, st.class_code]);
    let streak = 0;
    for (const r of recent) { if (r.log_id) streak++; else break; }
    res.json({
      name: st.name, adm: st.adm_no, classCode: st.class_code,
      attendancePercentage: Number(st.attendance_pct), points: st.points,
      rank: rank ? `${rank} / ${board.length}` : '—', streak, sessionsHeld: await sessionsHeld(st.class_code),
    });
  }),

  history: wrap(async (req, res) => {
    const st = await me(req);
    if (!st) return bad(res, 'No student record is linked to this account.', 404);
    const rows = await q(
      `SELECT s.id, s.unit_name, s.start_time, l.id AS log_id, l.is_late, l.timestamp AS scanned
       FROM sessions s LEFT JOIN attendance_logs l ON l.session_id = s.id AND l.adm_no = ?
       WHERE s.class_code = ? ORDER BY s.start_time DESC, s.id DESC LIMIT 60`, [st.adm_no, st.class_code]);
    res.json(rows.map((r) => ({
      id: r.id, date: fmtDate(r.start_time), unit: r.unit_name,
      time: r.log_id ? fmtTime(r.scanned) : '—', status: r.log_id ? (r.is_late ? 'Late' : 'Present') : 'Absent',
    })));
  }),

  eligibility: wrap(async (req, res) => {
    const st = await me(req);
    if (!st) return bad(res, 'No student record is linked to this account.', 404);
    const held = await sessionsHeld(st.class_code);
    const attended = (await one('SELECT COUNT(DISTINCT l.session_id) AS n FROM attendance_logs l JOIN sessions s ON s.id = l.session_id WHERE l.adm_no = ? AND s.class_code = ?', [st.adm_no, st.class_code])).n;
    const pct = Number(st.attendance_pct);
    const needed = Math.max(0, Math.ceil((T / 100) * held) - attended);
    res.json({
      attendancePct: pct, threshold: T, isEligible: pct >= T, sessionsHeld: held, sessionsAttended: attended,
      reason: pct >= T ? 'You meet the minimum attendance requirement for exams.' : `Attendance is below ${T}%. Attend at least ${needed} more session(s) (without further absences) to become eligible.`,
    });
  }),

  leaderboard: wrap(async (req, res) => {
    const st = await me(req);
    if (!st) return bad(res, 'No student record is linked to this account.', 404);
    const rows = await q('SELECT s.adm_no, s.points, u.name FROM students s JOIN users u ON u.id = s.user_id WHERE u.class_code = ? AND u.status = ? ORDER BY s.points DESC, u.name ASC', [st.class_code, 'active']);
    const board = rows.map((r, i) => ({ rank: i + 1, name: r.name, adm: r.adm_no, points: r.points, isMe: r.adm_no === st.adm_no }));
    res.json({ total: board.length, myRank: board.find((b) => b.isMe)?.rank || null, top: board.slice(0, 20) });
  }),

  chatList: wrap(async (req, res) => {
    const cc = classOf(req);
    const rows = await q('SELECT m.*, u.name FROM chat_messages m JOIN users u ON u.id = m.sender_id WHERE m.class_code = ? ORDER BY m.id DESC LIMIT 100', [cc]);
    res.json(rows.reverse().map((m) => ({ ...announcementOut(m), mine: m.sender_id === req.user.id })));
  }),
  chatSend: wrap((req, res) => postChat(req, res, false)),

  tempIdList: wrap(async (req, res) => {
    const adm = await admOf(req);
    const rows = await q('SELECT id, reason, status, created_at, expires_at FROM temp_id_requests WHERE adm_no = ? ORDER BY id DESC LIMIT 10', [adm]);
    res.json(rows.map((r) => ({ id: r.id, reason: r.reason, status: r.status, requested: fmtDate(r.created_at), expires: r.status === 'approved' ? `${fmtDate(r.expires_at)} ${fmtTime(r.expires_at)}` : null })));
  }),
  tempIdRequest: wrap(async (req, res) => {
    const adm = await admOf(req);
    if (!adm) return bad(res, 'No student record is linked to this account.', 404);
    const reason = String(req.body.reason || '').trim();
    if (!reason) return bad(res, 'Please give a reason (e.g. lost or damaged ID).');
    if (await one("SELECT id FROM temp_id_requests WHERE adm_no = ? AND status = 'pending'", [adm])) return bad(res, 'You already have a pending request.', 409);
    // face_score is NOT NULL in the schema; no face matching exists yet, so 0 means "not scored".
    const r = await exec('INSERT INTO temp_id_requests (adm_no, face_score, status, expires_at, reason) VALUES (?, 0, ?, ?, ?)', [adm, 'pending', sqlDate(HOURS(24)), reason]);
    res.status(201).json({ message: 'Request submitted. Your class rep will review it.', id: r.insertId });
  }),
};

// =========================================================================================
// CLASS REP
// =========================================================================================
export const rep = {
  lecturers: wrap(async (req, res) => res.json(await q("SELECT id, name FROM users WHERE role = 'teacher' AND status = 'active' ORDER BY name"))),

  sessionStart: wrap(async (req, res) => {
    const cc = classOf(req);
    const { unit_name, lecturer_name, venue, late_threshold_mins } = req.body;
    if (!cc) return bad(res, 'Your account has no class assigned.');
    if (!String(unit_name || '').trim() || !String(lecturer_name || '').trim()) return bad(res, 'Unit and lecturer are required.');
    const startedAt = new Date();
    await exec('UPDATE sessions SET is_active = 0, ended_at = COALESCE(ended_at, ?) WHERE class_code = ? AND is_active = 1', [sqlDate(startedAt), cc]);
    const r = await exec(
      'INSERT INTO sessions (class_code, unit_name, lecturer_name, start_time, end_time, late_threshold_mins, is_active, venue) VALUES (?, ?, ?, ?, ?, ?, 1, ?)',
      [cc, unit_name.trim(), lecturer_name.trim(), sqlDate(startedAt), sqlDate(new Date(startedAt.getTime() + 3 * 3600 * 1000)), Number(late_threshold_mins) || 15, venue || null]);
    await recomputeClassAttendance(cc); // a new session lowers the % of everyone who hasn't attended yet
    res.status(201).json({ id: r.insertId, class_code: cc, unit_name: unit_name.trim(), lecturer_name: lecturer_name.trim(), venue: venue || null });
  }),
  sessionCurrent: wrap(async (req, res) => {
    const s = await one('SELECT * FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [classOf(req)]);
    res.json({ session: s ? { id: s.id, unit_name: s.unit_name, lecturer_name: s.lecturer_name, venue: s.venue, startedAt: fmtTime(s.start_time) } : null });
  }),
  manualAttendanceList: wrap(async (req, res) => {
    const cc = classOf(req);
    if (!cc) return bad(res, 'Your account has no class assigned.');
    const session = await one('SELECT id, unit_name, start_time, late_threshold_mins FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [cc]);
    if (!session) return res.json({ session: null, students: [] });
    const students = await q(
      `SELECT s.adm_no, u.name, l.id AS attendance_id, l.timestamp AS attendance_time, l.is_late, l.record_method
       FROM students s JOIN users u ON u.id = s.user_id
       LEFT JOIN attendance_logs l ON l.adm_no = s.adm_no AND l.session_id = ?
       WHERE u.class_code = ? AND u.role = 'student' AND u.status = 'active'
       ORDER BY u.name, s.adm_no`, [session.id, cc]);
    res.json({
      session: { id: session.id, unit: session.unit_name, startedAt: fmtTime(session.start_time) },
      students: students.map((student) => ({
        adm: student.adm_no, name: student.name, present: !!student.attendance_id,
        time: student.attendance_time ? fmtTime(student.attendance_time) : null,
        late: student.attendance_id ? !!student.is_late : null,
        method: student.record_method || null,
      })),
    });
  }),
  manualAttendanceMark: wrap(async (req, res) => {
    const cc = classOf(req);
    const adm = String(req.body.adm_no || '').trim();
    if (!cc) return bad(res, 'Your account has no class assigned.');
    if (!adm || adm.length > 50) return bad(res, 'A valid student admission number is required.');
    const session = await one('SELECT * FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [cc]);
    if (!session) return bad(res, 'There is no active session. Start a session before recording attendance.', 409);
    const student = await one(
      "SELECT s.adm_no, u.name FROM students s JOIN users u ON u.id = s.user_id WHERE LOWER(s.adm_no) = LOWER(?) AND u.class_code = ? AND u.role = 'student' AND u.status = 'active'",
      [adm, cc]);
    if (!student) return bad(res, 'That active student is not registered in your class.', 404);
    if (await one('SELECT id FROM attendance_logs WHERE session_id = ? AND adm_no = ?', [session.id, student.adm_no])) {
      return bad(res, `${student.name} is already marked present for this session.`, 409);
    }

    const now = new Date();
    const isLate = (now - asDate(session.start_time)) / 60000 > (session.late_threshold_mins || 15);
    const points = isLate ? POINTS_LATE : POINTS_ON_TIME;
    let log;
    try {
      log = await exec(
        `INSERT INTO attendance_logs (session_id, adm_no, is_late, is_offline_synced, points_earned, record_method, recorded_by, timestamp)
         VALUES (?, ?, ?, 0, ?, 'manual', ?, ?)`,
        [session.id, student.adm_no, isLate ? 1 : 0, points, req.user.id, sqlDate(now)]);
    } catch (err) {
      if (err?.code === 'ER_DUP_ENTRY' || err?.code === 'SQLITE_CONSTRAINT_UNIQUE' || /unique constraint failed/i.test(err?.message || '')) {
        return bad(res, `${student.name} is already marked present for this session.`, 409);
      }
      throw err;
    }
    await exec('UPDATE students SET points = points + ? WHERE adm_no = ?', [points, student.adm_no]);
    await exec('INSERT INTO points_logs (adm_no, points, activity_type) VALUES (?, ?, ?)', [student.adm_no, points, isLate ? 'Manual late attendance' : 'Manual on-time attendance']);
    await recomputeAttendance(student.adm_no, cc);
    await awardBadges(student.adm_no);
    req.app.get('io')?.to(cc).emit('attendance_update', { class_code: cc, adm_no: student.adm_no, name: student.name, is_late: isLate });
    res.status(201).json({ message: `${student.name} marked present${isLate ? ' (late)' : ''}.`, is_late: isLate, points_earned: points, logId: log.insertId });
  }),
  sessionEnd: wrap(async (req, res) => { await exec('UPDATE sessions SET is_active = 0, ended_at = ? WHERE class_code = ? AND is_active = 1', [sqlDate(), classOf(req)]); res.json({ message: 'Session ended.' }); }),

  dashboard: wrap(async (req, res) => {
    const cc = classOf(req);
    const cls = await one('SELECT * FROM classes WHERE class_code = ?', [cc]);
    const students = await classStudents(cc);
    const todays = await q(
      'SELECT l.adm_no, MIN(l.is_late) AS min_late FROM attendance_logs l JOIN sessions s ON s.id = l.session_id WHERE s.class_code = ? AND l.timestamp >= ? GROUP BY l.adm_no', [cc, startOfToday()]);
    const sessionsToday = (await one('SELECT COUNT(*) AS n FROM sessions WHERE class_code = ? AND start_time >= ?', [cc, startOfToday()])).n;
    const present = todays.filter((t) => !t.min_late).length;
    const late = todays.length - present;
    const active = await one('SELECT id, unit_name FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [cc]);
    res.json({
      className: cls ? `${cls.course} (${cc})` : cc, classCode: cc, totalStudents: students.length,
      presentToday: present, lateToday: late, absentToday: sessionsToday ? Math.max(0, students.length - todays.length) : 0,
      atRiskCount: students.filter((s) => Number(s.attendance_pct) < T).length, activeSession: active ? { id: active.id, unit: active.unit_name } : null,
    });
  }),

  liveLogs: wrap(async (req, res) => {
    const cc = classOf(req);
    const session = (await one('SELECT * FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [cc])) || (await one('SELECT * FROM sessions WHERE class_code = ? ORDER BY id DESC LIMIT 1', [cc]));
    if (!session) return res.json({ session: null, total: (await classStudents(cc)).length, logs: [] });
    const rows = await q(
      `SELECT l.id, l.adm_no, l.timestamp, l.is_late, l.is_offline_synced, l.record_method, marked_by.name AS recorded_by, u.name FROM attendance_logs l
       JOIN students st ON st.adm_no = l.adm_no JOIN users u ON u.id = st.user_id
       LEFT JOIN users marked_by ON marked_by.id = l.recorded_by WHERE l.session_id = ? ORDER BY l.id DESC`, [session.id]);
    res.json({
      session: { id: session.id, unit: session.unit_name, active: !!session.is_active, startedAt: fmtTime(session.start_time) },
      total: (await classStudents(cc)).length,
      logs: rows.map((r) => ({ id: r.id, name: r.name, adm: r.adm_no, time: fmtTime(r.timestamp), status: r.is_late ? 'Late' : 'Present', offline: !!r.is_offline_synced, method: r.record_method || 'qr', recordedBy: r.recorded_by || null })),
    });
  }),

  members: wrap(async (req, res) => {
    const rows = await classStudents(classOf(req));
    res.json(rows.map((s) => ({ adm: s.adm_no, name: s.name, email: s.email, parent_email: s.parent_email, attendance: Number(s.attendance_pct), points: s.points, role: s.role, atRisk: Number(s.attendance_pct) < T })));
  }),
  memberAdd: wrap(async (req, res) => {
    const cc = classOf(req);
    const admNo = String(req.body.adm_no || '').trim().toUpperCase();
    const name = String(req.body.name || '').trim();
    const email = String(req.body.email || '').trim().toLowerCase();
    const password = String(req.body.password || '');
    const parentEmail = String(req.body.parent_email || '').trim().toLowerCase();
    const parentPhone = String(req.body.parent_phone || '').trim();
    if (!admNo || !name || !email || !password) return bad(res, 'Admission number, name, email and password are required.');
    if (password.length < 8) return bad(res, 'Password must be at least 8 characters.');
    if (admNo.length > 50 || name.length > 150 || email.length > 255 || parentEmail.length > 255 || parentPhone.length > 50) return bad(res, 'One or more fields exceed the maximum allowed length.');
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) || (parentEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(parentEmail))) return bad(res, 'Enter a valid email address.');

    const connection = await pool.getConnection();
    let uniqueField = 'email';
    try {
      await connection.beginTransaction();
      const [emails] = await connection.query('SELECT id FROM users WHERE LOWER(email) = ?', [email]);
      if (emails[0]) {
        await connection.rollback();
        return bad(res, 'An account with this email already exists.', 409);
      }
      const [admissions] = await connection.query('SELECT id FROM students WHERE LOWER(adm_no) = ?', [admNo.toLowerCase()]);
      if (admissions[0]) {
        await connection.rollback();
        return bad(res, 'This admission number is already registered.', 409);
      }

      const [user] = await connection.query(
        "INSERT INTO users (email, password, name, role, class_code, status) VALUES (?, ?, ?, 'student', ?, 'active')",
        [email, await bcrypt.hash(password, 10), name, cc]
      );
      uniqueField = 'admission number';
      await connection.query(
        'INSERT INTO students (user_id, adm_no, parent_email, parent_phone) VALUES (?, ?, ?, ?)',
        [user.insertId, admNo, parentEmail, parentPhone]
      );
      await connection.commit();
    } catch (err) {
      await connection.rollback();
      if (err?.code === 'ER_DUP_ENTRY' || err?.code === 'SQLITE_CONSTRAINT_UNIQUE' || /unique constraint failed/i.test(err?.message || '')) {
        return bad(res, uniqueField === 'email' ? 'An account with this email already exists.' : 'This admission number is already registered.', 409);
      }
      throw err;
    } finally {
      connection.release();
    }
    res.status(201).json({ adm: admNo, name, email, message: 'Student added. They can sign in using this email and the password you set.' });
  }),
  memberResetDevice: wrap(async (req, res) => {
    const target = await one('SELECT u.class_code FROM students s JOIN users u ON u.id = s.user_id WHERE s.adm_no = ?', [req.params.adm]);
    if (!target || (req.user.role !== 'admin' && target.class_code !== req.user.class_code)) return bad(res, 'Student not found in your class.', 404);
    await exec('DELETE FROM device_locks WHERE adm_no = ?', [req.params.adm]);
    res.json({ message: 'Device lock cleared. The student can register a new phone at their next sign-in.' });
  }),

  announcements: wrap(async (req, res) => {
    const rows = await q('SELECT m.*, u.name FROM chat_messages m JOIN users u ON u.id = m.sender_id WHERE m.class_code = ? AND m.is_announcement = 1 ORDER BY m.id DESC LIMIT 30', [classOf(req)]);
    res.json(rows.map(announcementOut));
  }),
  announce: wrap((req, res) => postChat(req, res, true)),
  chatList: student.chatList,
  chatSend: student.chatSend,

  timetable: wrap(async (req, res) => {
    const v = await one('SELECT * FROM timetable_versions WHERE class_code = ? ORDER BY id DESC LIMIT 1', [classOf(req)]);
    if (!v) return res.json({ version: null, slots: [] });
    const slots = await q('SELECT * FROM timetable_slots WHERE version_id = ?', [v.id]);
    slots.sort((a, b) => DAY_ORDER.indexOf(a.day_of_week.toLowerCase()) - DAY_ORDER.indexOf(b.day_of_week.toLowerCase()) || String(a.start_time).localeCompare(String(b.start_time)));
    res.json({
      version: { id: v.id, term: v.term, status: v.status, comment: v.hod_comment, uploaded: fmtDate(v.created_at), file: fileInfo(v) },
      slots: slots.map((s) => ({ id: s.id, day: s.day_of_week, time: `${String(s.start_time).slice(0, 5)} - ${String(s.end_time).slice(0, 5)}`, unit: s.unit_name, venue: s.venue, lecturer: s.lecturer_name })),
    });
  }),

  // Any file type. CSV/TSV/TXT files are ALSO read into a lesson table when they match: day,start,end,unit,venue,lecturer
  timetableUpload: wrap(async (req, res) => {
    const file = req.file;
    const discard = () => { if (file) fs.unlink(file.path, () => {}); };
    try {
      const cc = classOf(req);
      if (!file) return bad(res, 'Choose a file first.');
      if (!cc) { discard(); return bad(res, 'Your account has no class assigned.'); }
      const name = cleanName(Buffer.from(file.originalname, 'latin1').toString('utf8')); // multer hands over UTF-8 names as latin1
      const ext = safeExt(name);

      const slots = []; let skipped = 0;
      if (['csv', 'tsv', 'txt'].includes(ext)) {
        const lines = fs.readFileSync(file.path, 'utf8').replace(/^\uFEFF/, '').split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
        for (const line of lines) {
          const c = line.split(/[,;\t]/).map((x) => x.trim().replace(/^"|"$/g, ''));
          if (c[0]?.toLowerCase() === 'day') continue; // header row
          const [day, start, end, unit, venue, lecturer] = c;
          if (DAY_ORDER.includes((day || '').toLowerCase()) && /^\d{1,2}:\d{2}$/.test(start || '') && /^\d{1,2}:\d{2}$/.test(end || '') && unit) slots.push([day, start, end, unit, venue || 'TBA', lecturer || 'TBA']);
          else skipped++;
        }
      }

      const v = await exec(
        "INSERT INTO timetable_versions (class_code, term, status, file_name, file_path, file_type, file_size) VALUES (?, ?, 'pending', ?, ?, ?, ?)",
        [cc, req.body.term || 'Current term', name, path.basename(file.path), PREVIEW_TYPES[ext] || 'application/octet-stream', file.size]);
      for (const s of slots) await exec('INSERT INTO timetable_slots (version_id, day_of_week, start_time, end_time, unit_name, venue, lecturer_name) VALUES (?, ?, ?, ?, ?, ?, ?)', [v.insertId, ...s]);

      const note = slots.length ? ` ${slots.length} lesson(s) were also read into a table.` : '';
      res.status(201).json({
        version_id: v.insertId, slots: slots.length, skipped, file: { name, type: PREVIEW_TYPES[ext] || 'application/octet-stream', size: file.size, previewable: !!PREVIEW_TYPES[ext] },
        message: `"${name}" uploaded and sent to the HOD for approval.${note}`,
      });
    } catch (err) { discard(); throw err; }
  }),

  leaderboardReset: wrap(async (req, res) => {
    const cc = classOf(req);
    const top = (await classStudents(cc)).sort((a, b) => b.points - a.points).filter((s) => s.points > 0).slice(0, 3);
    const names = ['Weekly Champion', 'Weekly Runner-up', 'Weekly Third Place'];
    for (const [i, s] of top.entries()) await exec('INSERT INTO badges (adm_no, badge_name) VALUES (?, ?)', [s.adm_no, names[i]]);
    for (const s of await classStudents(cc)) await exec('UPDATE students SET points = 0 WHERE adm_no = ?', [s.adm_no]);
    res.json({ message: 'Leaderboard reset for the new week.', winners: top.map((s, i) => ({ rank: i + 1, name: s.name, points: s.points })) });
  }),
  leaderboard: wrap(async (req, res) => {
    const rows = (await classStudents(classOf(req))).sort((a, b) => b.points - a.points);
    res.json(rows.map((s, i) => ({ rank: i + 1, name: s.name, adm: s.adm_no, points: s.points })));
  }),

  ministryExport: wrap(async (req, res) => {
    const cc = classOf(req);
    const rows = (await classStudents(cc)).map((s) => [s.adm_no, s.name, `${Number(s.attendance_pct).toFixed(1)}%`, Number(s.attendance_pct) >= T ? 'Eligible' : 'Barred']);
    const headers = ['Adm No', 'Name', 'Attendance', 'Exam status'];
    const fmt = String(req.query.format || 'pdf').toLowerCase();
    if (fmt === 'csv') return sendCsv(res, `attendance-${cc.replace(/\W+/g, '_')}.csv`, headers, rows);
    sendPdf(res, `attendance-${cc.replace(/\W+/g, '_')}.pdf`, `MTTI Attendance Report: ${cc}`, `Generated ${fmtDate(new Date())} · ${rows.length} student(s) · minimum ${T}%`, headers, rows, [90, 220, 90, 100]);
  }),

  tempIds: wrap(async (req, res) => {
    const rows = await q(
      `SELECT t.id, t.adm_no, t.reason, t.created_at, u.name FROM temp_id_requests t JOIN students s ON s.adm_no = t.adm_no JOIN users u ON u.id = s.user_id
       WHERE u.class_code = ? AND t.status = 'pending' ORDER BY t.id DESC`, [classOf(req)]);
    res.json(rows.map((r) => ({ id: r.id, name: r.name, adm: r.adm_no, reason: r.reason || 'Temporary ID request', time: `${fmtDate(r.created_at)} ${fmtTime(r.created_at)}` })));
  }),
  tempIdDecision: wrap(async (req, res) => {
    const decision = req.body.decision === 'approved' ? 'approved' : req.body.decision === 'rejected' ? 'rejected' : null;
    if (!decision) return bad(res, 'decision must be "approved" or "rejected".');
    const t = await one('SELECT t.id, u.class_code FROM temp_id_requests t JOIN students s ON s.adm_no = t.adm_no JOIN users u ON u.id = s.user_id WHERE t.id = ?', [req.params.id]);
    if (!t || (req.user.role !== 'admin' && t.class_code !== req.user.class_code)) return bad(res, 'Request not found in your class.', 404);
    await exec('UPDATE temp_id_requests SET status = ?, expires_at = ? WHERE id = ?', [decision, sqlDate(HOURS(24)), t.id]);
    res.json({ message: decision === 'approved' ? 'Approved. The temporary ID is valid for 24 hours.' : 'Request rejected.' });
  }),

  parentAlerts: wrap(async (req, res) => {
    const rows = await q(
      `SELECT a.id, a.adm_no, a.parent_email, a.alert_reason, a.sent_at, a.delivery, u.name FROM parent_alerts a
       JOIN students s ON s.adm_no = a.adm_no JOIN users u ON u.id = s.user_id WHERE u.class_code = ? ORDER BY a.id DESC LIMIT 100`, [classOf(req)]);
    res.json(rows.map((r) => ({ id: r.id, student: r.name, adm: r.adm_no, parent: r.parent_email, reason: r.alert_reason, time: `${fmtDate(r.sent_at)} ${fmtTime(r.sent_at)}`, delivery: r.delivery })));
  }),
  parentAlertsRun: wrap(async (req, res) => {
    const cc = classOf(req);
    let created = 0, emailed = 0, skipped = 0;
    for (const s of (await classStudents(cc)).filter((x) => Number(x.attendance_pct) < T)) {
      const already = await one('SELECT id FROM parent_alerts WHERE adm_no = ? AND sent_at >= ?', [s.adm_no, startOfToday()]);
      if (!s.parent_email || already) { skipped++; continue; }
      const reason = `Attendance has dropped to ${Number(s.attendance_pct).toFixed(1)}% (minimum ${T}% required for exams).`;
      let delivery = 'logged';
      if (isEmailConfigured()) {
        try { await sendEmail({ to: s.parent_email, ...emailTemplates.parentAlert(s.name, reason) }); delivery = 'emailed'; emailed++; }
        catch { delivery = 'logged (email failed)'; }
      } else delivery = 'logged (email not configured)';
      await exec('INSERT INTO parent_alerts (adm_no, parent_email, alert_reason, delivery) VALUES (?, ?, ?, ?)', [s.adm_no, s.parent_email, reason, delivery]);
      created++;
    }
    res.json({ created, emailed, skipped, message: `${created} alert(s) recorded, ${emailed} emailed.` });
  }),
};

// =========================================================================================
// TEACHER
// =========================================================================================
async function lecturerSessions(req) {
  const name = (await one('SELECT name FROM users WHERE id = ?', [req.user.id]))?.name || '';
  return req.user.role === 'admin'
    ? q('SELECT * FROM sessions ORDER BY start_time DESC, id DESC LIMIT 100')
    : q('SELECT * FROM sessions WHERE LOWER(lecturer_name) = LOWER(?) ORDER BY start_time DESC, id DESC LIMIT 100', [name]);
}

async function absenteeismFor(sessions) {
  const groups = new Map();
  for (const s of sessions) { const k = `${s.class_code}|${s.unit_name}`; (groups.get(k) || groups.set(k, []).get(k)).push(s.id); }
  const out = [];
  for (const [key, ids] of groups) {
    const [classCode, unit] = key.split('|');
    const roster = await classStudents(classCode);
    const counts = await q(`SELECT adm_no, COUNT(*) AS n FROM attendance_logs WHERE session_id IN (${ids.map(() => '?').join(',')}) GROUP BY adm_no`, ids);
    const map = new Map(counts.map((c) => [c.adm_no, c.n]));
    const atRisk = roster.map((s) => ({ name: s.name, adm: s.adm_no, attendance: pct1(map.get(s.adm_no) || 0, ids.length) })).filter((s) => s.attendance < T).sort((a, b) => a.attendance - b.attendance);
    const attended = [...map.values()].reduce((a, b) => a + b, 0);
    out.push({ unit, classCode, sessions: ids.length, enrolled: roster.length, averageAttendance: pct1(attended, ids.length * roster.length), flagged: atRisk.length, atRiskStudents: atRisk });
  }
  return out;
}

export const teacher = {
  dashboard: wrap(async (req, res) => {
    const sessions = await lecturerSessions(req);
    const abs = await absenteeismFor(sessions);
    res.json({
      name: (await one('SELECT name FROM users WHERE id = ?', [req.user.id]))?.name,
      pendingSignoffs: sessions.filter((s) => !s.signed_at && !s.is_active).length,
      activeSessions: sessions.filter((s) => s.is_active).length,
      totalSessions: sessions.length, units: abs.length, atRiskStudents: abs.reduce((n, a) => n + a.flagged, 0),
    });
  }),
  sessions: wrap(async (req, res) => {
    const sessions = (await lecturerSessions(req)).slice(0, 50);
    const out = [];
    for (const s of sessions) {
      const present = (await one('SELECT COUNT(*) AS n FROM attendance_logs WHERE session_id = ?', [s.id])).n;
      const total = (await classStudents(s.class_code)).length;
      const repRow = await one('SELECT u.name FROM classes c JOIN users u ON u.id = c.rep_id WHERE c.class_code = ?', [s.class_code]) || await one("SELECT name FROM users WHERE role = 'student_rep' AND class_code = ? AND status = 'active'", [s.class_code]);
      out.push({ id: s.id, unit: s.unit_name, classCode: s.class_code, rep: repRow?.name || '—', date: fmtDate(s.start_time), time: fmtTime(s.start_time), present, total, signed: !!s.signed_at, active: !!s.is_active });
    }
    res.json(out);
  }),
  sign: wrap(async (req, res) => {
    const s = (await lecturerSessions(req)).find((x) => String(x.id) === String(req.params.id));
    if (!s) return bad(res, 'Session not found (or it is not one of your lessons).', 404);
    if (s.signed_at) return bad(res, 'This session is already signed.', 409);
    await exec('UPDATE sessions SET signed_by = ?, signed_at = ?, is_active = 0, ended_at = COALESCE(ended_at, ?) WHERE id = ?', [req.user.id, sqlDate(), sqlDate(), s.id]);
    res.json({ message: 'Attendance signed off.' });
  }),
  absenteeism: wrap(async (req, res) => res.json(await absenteeismFor(await lecturerSessions(req)))),
};

// =========================================================================================
// HOD
// =========================================================================================
async function allStudentsWithStats() {
  const rows = await q("SELECT s.adm_no, s.attendance_pct, u.name, u.class_code FROM students s JOIN users u ON u.id = s.user_id WHERE u.role IN ('student','student_rep') AND u.status = 'active' ORDER BY u.class_code, u.name");
  const held = new Map((await q('SELECT class_code, COUNT(*) AS n FROM sessions GROUP BY class_code')).map((r) => [r.class_code, r.n]));
  const att = new Map((await q('SELECT adm_no, COUNT(DISTINCT session_id) AS n FROM attendance_logs GROUP BY adm_no')).map((r) => [r.adm_no, r.n]));
  return rows.map((r) => ({ adm: r.adm_no, name: r.name, classCode: r.class_code, attendance: Number(r.attendance_pct), missed: Math.max(0, (held.get(r.class_code) || 0) - (att.get(r.adm_no) || 0)) }));
}

async function ministryPayload() {
  const students = await allStudentsWithStats();
  const byClass = new Map();
  for (const s of students) { const c = byClass.get(s.classCode) || { code: s.classCode, students: 0, sum: 0, eligible: 0 }; c.students++; c.sum += s.attendance; if (s.attendance >= T) c.eligible++; byClass.set(s.classCode, c); }
  const classes = [...byClass.values()].map((c) => ({ code: c.code, students: c.students, avgAttendance: Math.round((c.sum / c.students) * 10) / 10, eligible: c.eligible, barred: c.students - c.eligible }));
  return { generatedAt: new Date().toISOString(), threshold: T, classes, totals: { students: students.length, eligible: classes.reduce((n, c) => n + c.eligible, 0), barred: classes.reduce((n, c) => n + c.barred, 0) } };
}

export const hod = {
  dashboard: wrap(async (req, res) => {
    const students = await allStudentsWithStats();
    res.json({
      name: (await one('SELECT name FROM users WHERE id = ?', [req.user.id]))?.name,
      totalClasses: (await one('SELECT COUNT(*) AS n FROM classes')).n, totalStudents: students.length,
      departmentAttendance: students.length ? Math.round((students.reduce((n, s) => n + s.attendance, 0) / students.length) * 10) / 10 : 0,
      pendingRepApprovals: (await one("SELECT COUNT(*) AS n FROM users WHERE role = 'student_rep' AND status = 'pending'")).n,
      examBlocked: students.filter((s) => s.attendance < T).length,
      pendingTimetables: (await one("SELECT COUNT(*) AS n FROM timetable_versions WHERE status = 'pending'")).n,
    });
  }),
  classes: wrap(async (req, res) => {
    const classes = await q('SELECT c.class_code, c.course, c.module, u.name AS rep FROM classes c LEFT JOIN users u ON u.id = c.rep_id ORDER BY c.class_code');
    const stats = new Map((await q("SELECT u.class_code, COUNT(*) AS n, AVG(s.attendance_pct) AS avg FROM students s JOIN users u ON u.id = s.user_id WHERE u.status = 'active' GROUP BY u.class_code")).map((r) => [r.class_code, r]));
    const reps = new Map((await q("SELECT class_code, name FROM users WHERE role = 'student_rep' AND status = 'active'")).map((r) => [r.class_code, r.name]));
    res.json(classes.map((c) => ({ code: c.class_code, course: c.course, module: c.module, students: stats.get(c.class_code)?.n || 0, attendance: Math.round(Number(stats.get(c.class_code)?.avg || 0) * 10) / 10, rep: c.rep || reps.get(c.class_code) || 'Not assigned' })));
  }),
  pendingReps: wrap(async (req, res) => {
    const rows = await q("SELECT u.id, u.name, u.email, u.class_code, s.adm_no FROM users u LEFT JOIN students s ON s.user_id = u.id WHERE u.role = 'student_rep' AND u.status = 'pending' ORDER BY u.id");
    res.json(rows.map((r) => ({ id: r.id, name: r.name, email: r.email, adm: r.adm_no, classCode: r.class_code })));
  }),
  approveRep: wrap(async (req, res) => {
    const decision = req.body.decision === 'approve' ? 'approve' : req.body.decision === 'reject' ? 'reject' : null;
    if (!decision) return bad(res, 'decision must be "approve" or "reject".');
    const u = await one("SELECT id, class_code FROM users WHERE id = ? AND role = 'student_rep' AND status = 'pending'", [req.params.id]);
    if (!u) return bad(res, 'No pending class rep with that id.', 404);
    await exec('UPDATE users SET status = ? WHERE id = ?', [decision === 'approve' ? 'active' : 'rejected', u.id]);
    if (decision === 'approve') await exec('UPDATE classes SET rep_id = ? WHERE class_code = ?', [u.id, u.class_code]);
    res.json({ message: decision === 'approve' ? 'Class rep approved.' : 'Class rep rejected.' });
  }),
  atRisk: wrap(async (req, res) => res.json({ threshold: T, students: (await allStudentsWithStats()).filter((s) => s.attendance < T).sort((a, b) => a.attendance - b.attendance) })),
  finalReports: wrap(async (req, res) => {
    const p = await ministryPayload();
    res.json({ generatedOn: fmtDate(new Date()), threshold: T, totalStudents: p.totals.students, eligible: p.totals.eligible, barred: p.totals.barred, complianceRate: pct1(p.totals.eligible, p.totals.students), classes: p.classes });
  }),
  lostIdLogs: wrap(async (req, res) => {
    const rows = await q(
      `SELECT t.id, t.adm_no, t.status, t.reason, t.created_at, u.name, u.class_code FROM temp_id_requests t
       LEFT JOIN students s ON s.adm_no = t.adm_no LEFT JOIN users u ON u.id = s.user_id ORDER BY t.id DESC LIMIT 200`);
    res.json(rows.map((r) => ({ id: r.id, name: r.name || '—', adm: r.adm_no, classCode: r.class_code || '—', reason: r.reason || '—', time: `${fmtDate(r.created_at)} ${fmtTime(r.created_at)}`, status: r.status })));
  }),

  timetables: wrap(async (req, res) => {
    const rows = await q("SELECT v.id, v.class_code, v.term, v.status, v.created_at, v.file_name, v.file_path, v.file_type, v.file_size, (SELECT COUNT(*) FROM timetable_slots WHERE version_id = v.id) AS slot_count FROM timetable_versions v ORDER BY v.id DESC LIMIT 50");
    res.json(rows.map((r) => ({ id: r.id, classCode: r.class_code, term: r.term, status: r.status, slots: r.slot_count, date: fmtDate(r.created_at), file: fileInfo(r) })));
  }),
  timetableDecision: wrap(async (req, res) => {
    const decision = req.body.decision === 'approved' ? 'approved' : req.body.decision === 'rejected' ? 'rejected' : null;
    if (!decision) return bad(res, 'decision must be "approved" or "rejected".');
    const r = await exec('UPDATE timetable_versions SET status = ?, hod_comment = ? WHERE id = ?', [decision, req.body.comment || null, req.params.id]);
    if (!r.affectedRows) return bad(res, 'Timetable not found.', 404);
    res.json({ message: `Timetable ${decision}.` });
  }),

  ministryGenerate: wrap(async (req, res) => {
    const payload = await ministryPayload();
    const title = `Ministry Attendance Audit ${fmtDate(new Date())}`;
    const r = await exec('INSERT INTO ministry_reports (report_title, data_payload, generated_by) VALUES (?, ?, ?)', [title, JSON.stringify(payload), req.user.id]);
    res.status(201).json({ id: r.insertId, title, totals: payload.totals });
  }),
  ministryList: wrap(async (req, res) => {
    const rows = await q('SELECT id, report_title, created_at FROM ministry_reports ORDER BY id DESC LIMIT 50');
    res.json(rows.map((r) => ({ id: r.id, title: r.report_title, date: `${fmtDate(r.created_at)} ${fmtTime(r.created_at)}` })));
  }),
  ministryPdf: wrap(async (req, res) => {
    const r = await one('SELECT * FROM ministry_reports WHERE id = ?', [req.params.id]);
    if (!r) return bad(res, 'Report not found.', 404);
    const p = typeof r.data_payload === 'string' ? JSON.parse(r.data_payload) : r.data_payload;
    sendPdf(res, `ministry-audit-${r.id}.pdf`, r.report_title, `Generated ${fmtDate(r.created_at)} · minimum attendance ${p.threshold}% · ${p.totals.students} students, ${p.totals.eligible} eligible, ${p.totals.barred} barred`,
      ['Class', 'Students', 'Avg attendance', 'Eligible', 'Barred'], p.classes.map((c) => [c.code, c.students, `${c.avgAttendance}%`, c.eligible, c.barred]), [150, 80, 110, 80, 80]);
  }),

  // Students/reps are bound to the first device they sign in on. This lists them (any class) and shows who has one registered.
  devices: wrap(async (req, res) => {
    const search = String(req.query.search || '').trim().toLowerCase().slice(0, 60), cc = String(req.query.class_code || '').trim();
    const where = ["u.status = 'active'"], params = [];
    if (cc) { where.push('u.class_code = ?'); params.push(cc); }
    if (search) { where.push('(LOWER(u.name) LIKE ? OR LOWER(s.adm_no) LIKE ? OR LOWER(u.email) LIKE ?)'); const like = `%${search}%`; params.push(like, like, like); }
    const rows = await q(`SELECT s.adm_no, u.name, u.email, u.class_code, u.role, d.id AS lock_id, d.updated_at AS since
      FROM students s JOIN users u ON u.id = s.user_id LEFT JOIN device_locks d ON d.adm_no = s.adm_no
      WHERE ${where.join(' AND ')} ORDER BY u.name LIMIT 201`, params);
    res.json({
      truncated: rows.length > 200, // the fingerprint itself is never sent, only whether one is registered
      students: rows.slice(0, 200).map((r) => ({ adm: r.adm_no, name: r.name, email: r.email, classCode: r.class_code, role: r.role, registered: !!r.lock_id, since: r.since ? `${fmtDate(r.since)} ${fmtTime(r.since)}` : null })),
    });
  }),
  resetDevice: wrap(async (req, res) => {
    const st = await one('SELECT s.adm_no, u.name FROM students s JOIN users u ON u.id = s.user_id WHERE s.adm_no = ?', [req.params.adm]);
    if (!st) return bad(res, 'Unknown admission number.', 404);
    const r = await exec('DELETE FROM device_locks WHERE adm_no = ?', [st.adm_no]);
    res.json({ message: r.affectedRows ? `${st.name}'s registered device was cleared. They can sign in on their new device now, and it becomes their registered one.` : `${st.name} has no registered device yet, so there was nothing to clear.` });
  }),
  setFees: wrap(async (req, res) => {
    const total = Number(req.body.total_fees), paid = Number(req.body.paid_amount);
    if (!Number.isFinite(total) || !Number.isFinite(paid) || total < 0 || paid < 0) return bad(res, 'total_fees and paid_amount must be non-negative numbers.');
    if (!(await one('SELECT id FROM students WHERE adm_no = ?', [req.params.adm]))) return bad(res, 'Unknown admission number.', 404);
    if (await one('SELECT adm_no FROM fee_accounts WHERE adm_no = ?', [req.params.adm])) await exec('UPDATE fee_accounts SET total_fees = ?, paid_amount = ?, updated_at = ? WHERE adm_no = ?', [total, paid, sqlDate(), req.params.adm]);
    else await exec('INSERT INTO fee_accounts (adm_no, total_fees, paid_amount) VALUES (?, ?, ?)', [req.params.adm, total, paid]);
    res.json({ message: 'Fee account saved.' });
  }),
};

// =========================================================================================
// CAMPUS SERVICES (library, games, fees)
// =========================================================================================
const CAPACITY = Number(process.env.LIBRARY_CAPACITY) || 100;
async function libraryState(adm) {
  const ev = await q("SELECT adm_no, status_details FROM campus_checkins WHERE service_type = 'library' AND created_at >= ? ORDER BY id", [startOfToday()]);
  const last = new Map(); ev.forEach((e) => last.set(e.adm_no, e.status_details));
  return { currentOccupancy: [...last.values()].filter((v) => v === 'in').length, maxCapacity: CAPACITY, dailyVisits: ev.filter((e) => e.status_details === 'in').length, checkedIn: last.get(adm) === 'in' };
}

export const campus = {
  libraryStatus: wrap(async (req, res) => res.json(await libraryState(await admOf(req)))),
  libraryCheck: (direction) => wrap(async (req, res) => {
    const adm = await admOf(req);
    if (!adm) return bad(res, 'Only students can use library check-in.', 403);
    const s = await libraryState(adm);
    if (direction === 'in' && s.checkedIn) return bad(res, 'You are already checked in.', 409);
    if (direction === 'out' && !s.checkedIn) return bad(res, 'You are not checked in.', 409);
    if (direction === 'in' && s.currentOccupancy >= s.maxCapacity) return bad(res, 'The library is at capacity.', 409);
    await exec("INSERT INTO campus_checkins (adm_no, service_type, status_details) VALUES (?, 'library', ?)", [adm, direction]);
    res.status(201).json({ message: direction === 'in' ? 'Checked in to the library.' : 'Checked out. Thanks for visiting!', ...(await libraryState(adm)) });
  }),

  gamesList: wrap(async (req, res) => {
    const adm = await admOf(req);
    const rows = await q("SELECT id, status_details, created_at FROM campus_checkins WHERE adm_no = ? AND service_type = 'games' ORDER BY id DESC LIMIT 10", [adm]);
    res.json(rows.map((r) => ({ id: r.id, activity: r.status_details, date: fmtDate(r.created_at), time: fmtTime(r.created_at) })));
  }),
  gamesRecord: wrap(async (req, res) => {
    const adm = await admOf(req);
    if (!adm) return bad(res, 'Only students can record games attendance.', 403);
    const activity = String(req.body.activity || 'Sports').trim().slice(0, 100);
    if (await one("SELECT id FROM campus_checkins WHERE adm_no = ? AND service_type = 'games' AND status_details = ? AND created_at >= ?", [adm, activity, startOfToday()])) return bad(res, `"${activity}" is already recorded for today.`, 409);
    await exec("INSERT INTO campus_checkins (adm_no, service_type, status_details) VALUES (?, 'games', ?)", [adm, activity]);
    res.status(201).json({ message: `${activity} attendance recorded.` });
  }),

  fees: wrap(async (req, res) => {
    const st = await me(req);
    if (!st) return res.json({ recorded: false, message: 'Fee clearance applies to students only.' });
    const f = await one('SELECT * FROM fee_accounts WHERE adm_no = ?', [st.adm_no]);
    if (!f) return res.json({ recorded: false, adm: st.adm_no, name: st.name, message: 'No fee record has been entered for you yet. Please contact the finance office.' });
    const balance = f.total_fees - f.paid_amount;
    res.json({ recorded: true, adm: st.adm_no, name: st.name, totalFees: f.total_fees, paidAmount: f.paid_amount, balance: Math.max(0, balance), isCleared: balance <= 0, updated: fmtDate(f.updated_at) });
  }),
};

// =========================================================================================
// ADMINISTRATOR: classes and staff accounts (replaces doing this by hand in the database)
// =========================================================================================
const STAFF_ROLES = ['teacher', 'hod', 'admin'];
const CLASS_CODE_RE = /^[A-Za-z0-9][A-Za-z0-9 /_.\-]{1,49}$/;
const staffById = (id) => one("SELECT id, name, email, role, status FROM users WHERE id = ? AND role IN ('teacher','hod','admin')", [id]);

export const admin = {
  dashboard: wrap(async (req, res) => {
    const by = Object.fromEntries((await q("SELECT role, COUNT(*) AS n FROM users WHERE status = 'active' GROUP BY role")).map((r) => [r.role, r.n]));
    res.json({
      name: (await one('SELECT name FROM users WHERE id = ?', [req.user.id]))?.name,
      students: by.student || 0, reps: by.student_rep || 0, teachers: by.teacher || 0, hods: by.hod || 0, admins: by.admin || 0,
      classes: (await one('SELECT COUNT(*) AS n FROM classes')).n,
      termStart: (await one("SELECT setting_value FROM app_settings WHERE setting_key = 'term_start'"))?.setting_value || null,
      pendingStaff: (await one("SELECT COUNT(*) AS n FROM users WHERE role IN ('teacher','hod','admin') AND status = 'pending'")).n,
      pendingReps: (await one("SELECT COUNT(*) AS n FROM users WHERE role = 'student_rep' AND status = 'pending'")).n,
    });
  }),

  classes: wrap(async (req, res) => {
    const rows = await q(`SELECT c.class_code, c.course, c.module, c.department,
      c.class_teacher_id, teacher.name AS class_teacher,
      (SELECT COUNT(*) FROM users u WHERE u.class_code = c.class_code AND u.role IN ('student','student_rep') AND u.status = 'active') AS students
      FROM classes c LEFT JOIN users teacher ON teacher.id = c.class_teacher_id AND teacher.role = 'teacher'
      ORDER BY c.class_code`);
    const reps = new Map((await q("SELECT class_code, name FROM users WHERE role = 'student_rep' AND status = 'active'")).map((r) => [r.class_code, r.name]));
    res.json(rows.map((c) => ({ code: c.class_code, course: c.course, module: c.module, department: c.department || '', classTeacherId: c.class_teacher_id, classTeacher: c.class_teacher || '', students: c.students, rep: reps.get(c.class_code) || 'Not assigned' })));
  }),
  classAdd: wrap(async (req, res) => {
    const code = String(req.body.class_code || '').trim(), course = String(req.body.course || '').trim(), module = String(req.body.module || '').trim();
    if (!CLASS_CODE_RE.test(code)) return bad(res, 'Class code must be 2-50 characters: letters, numbers, spaces and / _ . - only.');
    if (!course || course.length > 150) return bad(res, 'Course name is required (max 150 characters).');
    if (!module || module.length > 50) return bad(res, 'Module is required (max 50 characters).');
    const department = String(req.body.department || '').trim();
    if (department.length > 100) return bad(res, 'Department is too long (max 100 characters).');
    const teacherValue = req.body.class_teacher_id;
    let classTeacherId = null;
    if (teacherValue !== undefined && teacherValue !== null && teacherValue !== '') {
      classTeacherId = Number(teacherValue);
      if (!Number.isSafeInteger(classTeacherId) || classTeacherId < 1) return bad(res, 'Choose a valid active class teacher.');
      if (!(await one("SELECT id FROM users WHERE id = ? AND role = 'teacher' AND status = 'active'", [classTeacherId]))) return bad(res, 'The selected class teacher is not an active teacher.', 400);
    }
    if (await one('SELECT class_code FROM classes WHERE LOWER(class_code) = LOWER(?)', [code])) return bad(res, `Class ${code} already exists.`, 409);
    await exec('INSERT INTO classes (class_code, course, module, department, class_teacher_id) VALUES (?, ?, ?, ?, ?)', [code, course, module, department || null, classTeacherId]);
    res.status(201).json({ message: `Class ${code} added. Students and class reps can now register for it.`, code });
  }),
  classUpdate: wrap(async (req, res) => {
    const code = String(req.body.class_code || '').trim(), course = String(req.body.course || '').trim(), module = String(req.body.module || '').trim(), department = String(req.body.department || '').trim();
    const existing = await one('SELECT class_code, class_teacher_id FROM classes WHERE class_code = ?', [code]);
    if (!existing) return bad(res, 'Class not found.', 404);
    if (!course || course.length > 150) return bad(res, 'Course name is required (max 150 characters).');
    if (!module || module.length > 50) return bad(res, 'Module is required (max 50 characters).');
    if (department.length > 100) return bad(res, 'Department is too long (max 100 characters).');
    let classTeacherId = existing.class_teacher_id;
    if (Object.hasOwn(req.body, 'class_teacher_id')) {
      const teacherValue = req.body.class_teacher_id;
      classTeacherId = teacherValue === null || teacherValue === '' ? null : Number(teacherValue);
      if (classTeacherId !== null && (!Number.isSafeInteger(classTeacherId) || classTeacherId < 1)) return bad(res, 'Choose a valid active class teacher.');
      if (classTeacherId !== null && !(await one("SELECT id FROM users WHERE id = ? AND role = 'teacher' AND status = 'active'", [classTeacherId]))) return bad(res, 'The selected class teacher is not an active teacher.', 400);
    }
    await exec('UPDATE classes SET course = ?, module = ?, department = ?, class_teacher_id = ? WHERE class_code = ?', [course, module, department || null, classTeacherId, code]);
    res.json({ message: `Class ${code} updated.` });
  }),
  classDelete: wrap(async (req, res) => {
    const code = String(req.query.code || '');
    if (!(await one('SELECT class_code FROM classes WHERE class_code = ?', [code]))) return bad(res, 'Class not found.', 404);
    const members = (await one('SELECT COUNT(*) AS n FROM users WHERE class_code = ?', [code])).n;
    if (members) return bad(res, `Class ${code} has ${members} member(s) (including pending sign-ups) and can't be deleted.`, 409);
    const history = (await one('SELECT COUNT(*) AS n FROM sessions WHERE class_code = ?', [code])).n + (await one('SELECT COUNT(*) AS n FROM timetable_versions WHERE class_code = ?', [code])).n;
    if (history) return bad(res, `Class ${code} has recorded sessions or timetables and can't be deleted.`, 409);
    await exec('DELETE FROM classes WHERE class_code = ?', [code]);
    res.json({ message: `Class ${code} deleted.` });
  }),
  classMembers: wrap(async (req, res) => {
    const code = String(req.query.code || '').trim();
    if (!code) return bad(res, 'A class code is required.');
    if (!(await one('SELECT class_code FROM classes WHERE class_code = ?', [code]))) return bad(res, 'Class not found.', 404);
    const rows = await q(
      `SELECT u.id, s.adm_no, u.name, u.email, u.role, u.status, s.parent_email, s.parent_phone,
        s.attendance_pct, s.points
       FROM users u LEFT JOIN students s ON s.user_id = u.id
       WHERE u.class_code = ? AND u.role IN ('student', 'student_rep')
       ORDER BY u.name, u.id`, [code]);
    res.json(rows.map((r) => ({
      id: r.id, adm_no: r.adm_no, name: r.name, email: r.email, role: r.role, status: r.status,
      parent_email: r.parent_email || '', parent_phone: r.parent_phone || '',
      attendance: r.attendance_pct == null ? null : Number(r.attendance_pct),
      points: r.points == null ? null : Number(r.points),
    })));
  }),
  classMemberUpdate: wrap(async (req, res) => {
    const code = String(req.body.code || '').trim();
    const userId = Number(req.body.user_id);
    const name = String(req.body.name || '').trim();
    const email = String(req.body.email || '').trim().toLowerCase();
    const parentEmail = String(req.body.parent_email || '').trim().toLowerCase();
    const parentPhone = String(req.body.parent_phone || '').trim();
    if (!code || !Number.isInteger(userId) || userId < 1) return bad(res, 'A class code and valid user ID are required.');
    if (!name || name.length > 150) return bad(res, 'Name is required and must be 150 characters or fewer.');
    if (email.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return bad(res, 'Enter a valid email address.');
    if (parentEmail && (parentEmail.length > 254 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(parentEmail))) return bad(res, 'Enter a valid parent email address or leave it blank.');
    if (parentPhone.length > 50) return bad(res, 'Parent phone must be 50 characters or fewer.');
    const member = await one("SELECT id FROM users WHERE id = ? AND class_code = ? AND role IN ('student', 'student_rep')", [userId, code]);
    if (!member) return bad(res, 'Member not found in this class.', 404);
    if (await one('SELECT id FROM users WHERE email = ? AND id <> ?', [email, userId])) return bad(res, 'An account with this email already exists.', 409);

    const connection = await pool.getConnection();
    try {
      await connection.beginTransaction();
      await connection.query('UPDATE users SET name = ?, email = ? WHERE id = ?', [name, email, userId]);
      await connection.query('UPDATE students SET parent_email = ?, parent_phone = ? WHERE user_id = ?', [parentEmail, parentPhone, userId]);
      await connection.commit();
    } catch (err) {
      await connection.rollback();
      throw err;
    } finally {
      connection.release();
    }
    res.json({ message: `${name}'s details updated.` });
  }),
  classMemberDelete: wrap(async (req, res) => {
    const code = String(req.query.code || '').trim();
    const userId = Number(req.query.user_id);
    if (!code || !Number.isInteger(userId) || userId < 1) return bad(res, 'A class code and valid user ID are required.');
    const connection = await pool.getConnection();
    let photos = [];
    try {
      await connection.beginTransaction();
      const [users] = await connection.query(
        "SELECT id, class_code, role FROM users WHERE id = ? AND role IN ('student', 'student_rep') FOR UPDATE", [userId]);
      const member = users[0];
      if (!member || member.class_code !== code) {
        await connection.rollback();
        return bad(res, 'Member not found in this class.', 404);
      }
      const [students] = await connection.query('SELECT adm_no FROM students WHERE user_id = ?', [userId]);
      const admNo = students[0]?.adm_no;
      if (admNo) {
        const [attendance] = await connection.query('SELECT photo_url FROM attendance_logs WHERE adm_no = ? AND photo_url IS NOT NULL', [admNo]);
        photos = attendance.map((row) => row.photo_url).filter(Boolean);
        for (const table of ['attendance_logs', 'device_locks', 'parent_alerts', 'points_logs', 'badges', 'temp_id_requests', 'campus_checkins']) {
          await connection.query(`DELETE FROM ${table} WHERE adm_no = ?`, [admNo]);
        }
      }
      if (member.role === 'student_rep') {
        await connection.query('UPDATE classes SET rep_id = NULL WHERE class_code = ? AND rep_id = ?', [code, userId]);
      }
      await connection.query('DELETE FROM users WHERE id = ?', [userId]);
      await connection.commit();
    } catch (err) {
      await connection.rollback();
      throw err;
    } finally {
      connection.release();
    }

    let failedPhotoCleanup = 0;
    for (const photo of photos) {
      const fullPath = path.resolve(photo);
      const relativePath = path.relative(UPLOAD_DIR, fullPath);
      if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) continue;
      try {
        await fs.promises.unlink(fullPath);
      } catch (err) {
        if (err.code !== 'ENOENT') {
          failedPhotoCleanup++;
          console.error(`Could not remove attendance photo after deleting member ${userId}:`, err);
        }
      }
    }

    res.json({
      message: failedPhotoCleanup
        ? `Member deleted, but ${failedPhotoCleanup} attendance photo(s) could not be removed.`
        : 'Member and related account records deleted.',
    });
  }),

  settings: wrap(async (req, res) => {
    const t = (await one("SELECT setting_value FROM app_settings WHERE setting_key = 'term_start'"))?.setting_value || null;
    const b = t ? weekBounds(t) : null;
    const now = weekBounds('');
    res.json({ termStart: t, currentWeek: b ? Math.max(0, Math.round((now.mon - b.mon) / (7 * 86400000)) + 1) || null : null });
  }),
  settingsSave: wrap(async (req, res) => {
    const v = String(req.body.term_start || '').trim();
    if (v && !weekBounds(v)) return bad(res, 'term_start must be a date like 2026-08-31 (the first day of week 1), or empty to clear it.');
    await exec("DELETE FROM app_settings WHERE setting_key = 'term_start'");
    if (v) await exec("INSERT INTO app_settings (setting_key, setting_value) VALUES ('term_start', ?)", [v]);
    const b = v ? weekBounds(v) : null;
    res.json({ message: v ? `Term starts in the week of ${dayLabel(b.mon)} ${b.mon.getFullYear()}. Printed registers now show the week number.` : 'Term start cleared. Registers will leave the week number blank.' });
  }),
  // Is outgoing email set up? (the password is never sent to the browser)
  emailStatus: wrap(async (req, res) => {
    const s = emailSettings();
    const mask = (e) => (e ? e.replace(/^(.{2}).*(@.*)$/, '$1***$2') : null);
    res.json({ configured: isEmailConfigured(), missing: missingEmailSettings(), host: s.host || null, port: s.port, secure: s.secure, user: mask(s.user), from: s.from || null, frontendUrl: s.frontendUrl || null });
  }),
  emailTest: wrap(async (req, res) => {
    if (!allow(`email-test:${req.user.id}`, 10)) return bad(res, 'Too many test emails. Wait a few minutes.', 429);
    const to = String(req.body.to || '').trim() || (await one('SELECT email FROM users WHERE id = ?', [req.user.id]))?.email;
    if (!to || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) return bad(res, 'Enter a valid email address to send the test to.');
    if (!isEmailConfigured()) return bad(res, describeEmailError({ code: 'ENOTCONFIGURED' }));
    try { await sendEmail({ to, ...emailTemplates.test() }); res.json({ message: `Test email sent to ${to}. Check the inbox (and the spam folder).` }); }
    catch (err) { return bad(res, describeEmailError(err), 502); }
  }),
  staff: wrap(async (req, res) => {
    const order = { pending: 0, active: 1, inactive: 2, rejected: 3 };
    const rows = await q("SELECT id, name, email, role, status FROM users WHERE role IN ('teacher','hod','admin') ORDER BY name");
    rows.sort((a, b) => (order[a.status] ?? 9) - (order[b.status] ?? 9));
    res.json(rows.map((r) => ({ ...r, isMe: r.id === req.user.id })));
  }),
  staffAdd: wrap(async (req, res) => {
    const { role, name, email, password } = req.body;
    if (!STAFF_ROLES.includes(role)) return bad(res, `Role must be one of: ${STAFF_ROLES.join(', ')}.`);
    if (!String(name || '').trim() || !String(email || '').trim()) return bad(res, 'Name and email are required.');
    if (String(password || '').length < 8) return bad(res, 'Password must be at least 8 characters.');
    if (await one('SELECT id FROM users WHERE email = ?', [email.trim()])) return bad(res, 'An account with this email already exists.', 409);
    const r = await exec("INSERT INTO users (email, password, name, role, status) VALUES (?, ?, ?, ?, 'active')", [email.trim(), await bcrypt.hash(password, 10), name.trim(), role]);
    res.status(201).json({ id: r.insertId, message: `${name.trim()} added as ${role}. Give them the password; they can sign in straight away.` });
  }),
  staffDecision: wrap(async (req, res) => {
    const decision = req.body.decision === 'approve' ? 'approve' : req.body.decision === 'reject' ? 'reject' : null;
    if (!decision) return bad(res, 'decision must be "approve" or "reject".');
    const u = await staffById(req.params.id);
    if (!u || u.status !== 'pending') return bad(res, 'No pending staff registration with that id.', 404);
    await exec('UPDATE users SET status = ? WHERE id = ?', [decision === 'approve' ? 'active' : 'rejected', u.id]);
    res.json({ message: `${u.name} ${decision === 'approve' ? 'approved' : 'rejected'}.` });
  }),
  staffStatus: wrap(async (req, res) => {
    const status = req.body.status === 'active' ? 'active' : req.body.status === 'inactive' ? 'inactive' : null;
    if (!status) return bad(res, 'status must be "active" or "inactive".');
    const u = await staffById(req.params.id);
    if (!u) return bad(res, 'Staff member not found.', 404);
    if (u.id === req.user.id) return bad(res, "You can't change your own status.");
    await exec('UPDATE users SET status = ? WHERE id = ?', [status, u.id]);
    res.json({ message: `${u.name} is now ${status}.` });
  }),
  staffPassword: wrap(async (req, res) => {
    const u = await staffById(req.params.id);
    if (!u) return bad(res, 'Staff member not found.', 404);
    if (String(req.body.password || '').length < 8) return bad(res, 'Password must be at least 8 characters.');
    await exec('UPDATE users SET password = ?, token_version = token_version + 1 WHERE id = ?', [await bcrypt.hash(req.body.password, 10), u.id]);
    res.json({ message: `Password updated for ${u.name}.` });
  }),
};

// =========================================================================================
// WEEKLY ATTENDANCE SHEET: who was present at each lesson Mon-Sun of a week, ready to print on Friday
// Class reps get their own class; HOD / admin pick any class.
// =========================================================================================
const DAY3 = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const MON3 = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const dayLabel = (d) => `${DAY3[d.getDay()]} ${String(d.getDate()).padStart(2, '0')} ${MON3[d.getMonth()]}`;
const isoDay = (d) => sqlDate(d).slice(0, 10);

// Monday 00:00 of the week containing `week` (YYYY-MM-DD, default today) .. the following Monday
function weekBounds(week) {
  if (week && !/^\d{4}-\d{2}-\d{2}$/.test(week)) return null;
  const base = week ? new Date(`${week}T00:00:00`) : new Date();
  if (Number.isNaN(base.getTime())) return null;
  base.setHours(0, 0, 0, 0);
  const mon = new Date(base); mon.setDate(base.getDate() - ((base.getDay() + 6) % 7));
  const next = new Date(mon); next.setDate(mon.getDate() + 7);
  const sun = new Date(mon); sun.setDate(mon.getDate() + 6);
  return { mon, next, sun };
}

// ----- The paper register, form MTTI/REG/CUR/01: one class page, 5 days x 4 lesson slots -----
const SLOTS = [
  { start: 8 * 60, label: ['8-10', 'am'] },
  { start: 10 * 60 + 30, label: ['10:30-', '12:30', 'pm'] },
  { start: 13 * 60 + 30, label: ['1:30-', '3:30', 'pm'] },
  { start: 15 * 60 + 35, label: ['3:35-', '5:35', 'pm'] },
];
// A lesson belongs to the slot whose start is the latest one at most 30 minutes after the lesson began
// (reps start the QR a little early or late). Before 7:30 it counts as the first slot, after 3:05 pm the last.
const slotIndex = (d) => { const t = d.getHours() * 60 + d.getMinutes(); let k = 0; SLOTS.forEach((s, i) => { if (t >= s.start - 30) k = i; }); return k; };
const hhmm = (v) => { const d = asDate(v); return Number.isNaN(d.getTime()) ? null : `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`; }; // null (printed blank) for a missing/garbled time
const hhmmSeconds = (v) => { const d = asDate(v); return Number.isNaN(d.getTime()) ? null : `${hhmm(v)}:${String(d.getSeconds()).padStart(2, '0')}`; };
const shortDate = (d) => `${d.getDate()} ${MON3[d.getMonth()]}`;
const FORM_NO = 'MTTI/REG/CUR/01';
const DAY_NAMES = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'];
const LOGO_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../assets/mtti-logo.png');
const generatedAt = (date) => `${new Intl.DateTimeFormat('en-GB', {
  timeZone: 'Africa/Nairobi', day: '2-digit', month: 'short', year: 'numeric',
  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true,
}).format(date)} EAT`;

async function buildWeeklySheet(cc, week) {
  const b = weekBounds(week);
  if (!b) return null;
  const cls = await one(`SELECT c.course, c.module, c.department, teacher.name AS class_teacher
    FROM classes c LEFT JOIN users teacher ON teacher.id = c.class_teacher_id AND teacher.role = 'teacher'
    WHERE c.class_code = ?`, [cc]);
  const sessions = await q('SELECT * FROM sessions WHERE class_code = ? AND start_time >= ? AND start_time < ? ORDER BY start_time, id', [cc, sqlDate(b.mon), sqlDate(b.next)]);
  const roster = await classStudents(cc);
  const marks = new Map(); // `${session}|${adm}` -> 'P' | 'L'
  if (sessions.length) {
    const ids = sessions.map((s) => s.id);
    for (const l of await q(`SELECT session_id, adm_no, is_late FROM attendance_logs WHERE session_id IN (${ids.map(() => '?').join(',')})`, ids)) marks.set(`${l.session_id}|${l.adm_no}`, l.is_late ? 'L' : 'P');
  }
  const students = roster.map((s) => {
    const m = sessions.map((x) => marks.get(`${x.id}|${s.adm_no}`) || 'A');
    const late = m.filter((v) => v === 'L').length, present = m.filter((v) => v !== 'A').length;
    return { adm: s.adm_no, name: s.name, marks: m, present, late, absent: m.length - present, pct: pct1(present, m.length) };
  });

  // Academic week number = weeks since the term start the Administrator configured (blank if not set)
  let weekNumber = null;
  const term = await one("SELECT setting_value FROM app_settings WHERE setting_key = 'term_start'");
  const t0 = term?.setting_value ? weekBounds(term.setting_value) : null;
  if (t0) { const n = Math.round((b.mon - t0.mon) / (7 * 86400000)) + 1; weekNumber = n >= 1 ? n : null; }

  // One register per subject (same unit + lecturer), each with its lessons placed in the Mon-Fri x 4-slot grid
  const groups = new Map();
  for (const s of sessions) {
    const k = `${(s.unit_name || '').trim().toLowerCase()}|${(s.lecturer_name || '').trim().toLowerCase()}`;
    if (!groups.has(k)) groups.set(k, { unit: s.unit_name, lecturer: s.lecturer_name, list: [] });
    groups.get(k).list.push(s);
  }
  let weekendSkipped = 0;
  const subjectsBySlot = new Map();
  const classCells = new Map();
  for (const s of sessions) {
    const st = asDate(s.start_time), day = (st.getDay() + 6) % 7;
    if (day > 4) continue;
    const key = day * 4 + slotIndex(st);
    const subjectsAtSlot = subjectsBySlot.get(key) || new Set();
    subjectsAtSlot.add(String(s.unit_name || '').trim());
    subjectsBySlot.set(key, subjectsAtSlot);
    const cell = classCells.get(key) || { day, slot: key % 4, ids: [], timeIn: null, timeOut: null, signed: true, allEnded: true };
    const tin = hhmmSeconds(s.start_time), tout = s.ended_at ? hhmmSeconds(s.ended_at) : null;
    cell.ids.push(s.id);
    if (tin && (!cell.timeIn || tin < cell.timeIn)) cell.timeIn = tin;
    if (tout && (!cell.timeOut || tout > cell.timeOut)) cell.timeOut = tout;
    cell.signed = cell.signed && !!s.signed_at;
    cell.allEnded = cell.allEnded && !!s.ended_at;
    classCells.set(key, cell);
  }
  const subjects = [...groups.values()].map((g) => {
    const cells = new Map();
    for (const s of g.list) {
      const st = asDate(s.start_time), day = (st.getDay() + 6) % 7;
      if (day > 4) { weekendSkipped++; continue; } // the register has Monday-Friday columns only
      const slot = slotIndex(st), key = day * 4 + slot;
      const c = cells.get(key) || { day, slot, ids: [], timeIn: null, timeOut: null, signed: true, allEnded: true };
      c.ids.push(s.id);
      const tin = hhmmSeconds(s.start_time);
      const tout = s.ended_at ? hhmmSeconds(s.ended_at) : null;
      if (tin && (!c.timeIn || tin < c.timeIn)) c.timeIn = tin;
      if (tout && (!c.timeOut || tout > c.timeOut)) c.timeOut = tout;
      c.signed = c.signed && !!s.signed_at;
      c.allEnded = c.allEnded && !!s.ended_at;
      cells.set(key, c);
    }
    return {
      unit: g.unit, lecturer: g.lecturer,
      cells: [...cells.entries()].sort((a, b2) => a[0] - b2[0]).map(([, c]) => ({ day: c.day, slot: c.slot, timeIn: c.timeIn, timeOut: c.allEnded ? c.timeOut : null, signed: c.signed })),
      rows: roster.map((st) => ({
        adm: st.adm_no, name: st.name,
        marks: Array.from({ length: 20 }, (_, i) => { const c = cells.get(i); return c ? (c.ids.some((id) => marks.has(`${id}|${st.adm_no}`)) ? 'P' : 'A') : null; }), // tick / cross / blank
      })),
    };
  });
  const classRegister = {
    cells: [...classCells.entries()].sort((a, b) => a[0] - b[0]).map(([, cell]) => ({ ...cell, timeOut: cell.allEnded ? cell.timeOut : null })),
    rows: roster.map((student) => ({
      adm: student.adm_no, name: student.name,
      marks: Array.from({ length: 20 }, (_, i) => {
        const cell = classCells.get(i);
        return cell ? (cell.ids.some((id) => marks.has(`${id}|${student.adm_no}`)) ? 'P' : 'A') : null;
      }),
    })),
  };

  const friday = new Date(b.mon); friday.setDate(b.mon.getDate() + 4);
  return {
    classCode: cc, course: cls ? `${cls.course} · ${cls.module}` : '', department: cls?.department || '',
    classTeacher: cls?.class_teacher || '',
    subjectsBySlot: [...subjectsBySlot.entries()].map(([slot, units]) => ({ slot, units: [...units].sort((a, b) => a.localeCompare(b)).join(' / ') })),
    classRegister,
    weekStart: isoDay(b.mon), weekEnd: isoDay(b.sun), weekLabel: `${dayLabel(b.mon)} - ${dayLabel(b.sun)} ${b.sun.getFullYear()}`,
    weekNumber, dateFrom: shortDate(b.mon), dateTo: shortDate(friday), year: b.mon.getFullYear(), weekendSkipped,
    sessions: sessions.map((s, i) => ({ n: i + 1, id: s.id, label: `${dayLabel(asDate(s.start_time))} ${fmtTime(s.start_time)}`, unit: s.unit_name, lecturer: s.lecturer_name, signed: !!s.signed_at })),
    students, subjects,
    totals: { students: students.length, sessions: sessions.length, presentStudents: students.filter((s) => s.present > 0).length, perfect: sessions.length ? students.filter((s) => s.absent === 0).length : 0 },
  };
}

// Draws the official register (landscape A4): logo + header fields, the 5-day x 4-slot grid, a tick for present,
// a cross for absent, blank where no lesson was held, then TEACHER'S SIGN and H.O.D'S COMMENTS.
function sendRegisterPdf(res, sh, filename) {
  const doc = new PDFDocument({ autoFirstPage: false, size: 'A4', layout: 'landscape', margin: 0 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  doc.pipe(res);

  const PW = 842, PH = 595, L = 20, R = PW - 20, BLACK = '#000';
  const wSN = 24, wADM = 50, wNAME = 112, slotW = (R - L - wSN - wADM - wNAME) / 20;
  const hDay = 14, hTime = 27, hIn = 13, hOut = 13, hSubject = 30, hLab = 15, hFoot = 16;
  const headH = hDay + hTime + hIn + hOut + hSubject + hLab, tableTop = 108;
  const availRows = PH - 24 - tableTop - headH - hFoot - 34; // vertical room for student rows
  const xADM = L + wSN, xNAME = xADM + wADM, xS = xNAME + wNAME;

  const box = (x, y, w, h) => { doc.save().lineWidth(0.5).strokeColor(BLACK).rect(x, y, w, h).stroke().restore(); };
  const label = (s, x, y, w, h, { size = 7, bold = false, align = 'center', color = BLACK } = {}) => {
    const text = String(s ?? '');
    doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fontSize(size).fillColor(color);
    const th = doc.heightOfString(text, { width: w - 3, align });
    doc.text(text, x + 1.5, y + Math.max(1, (h - th) / 2), { width: w - 3, height: h, align, ellipsis: true });
  };
  const tick = (cx, cy, scale = 1) => doc.save().lineWidth(1.3 * scale).lineCap('round').lineJoin('round').strokeColor(BLACK).moveTo(cx - 4.5 * scale, cy + 0.5 * scale).lineTo(cx - 1.5 * scale, cy + 3.8 * scale).lineTo(cx + 5 * scale, cy - 3.8 * scale).stroke().restore();
  const cross = (cx, cy, scale = 1) => doc.save().lineWidth(1.1 * scale).lineCap('round').strokeColor(BLACK).moveTo(cx - 3.5 * scale, cy - 3.5 * scale).lineTo(cx + 3.5 * scale, cy + 3.5 * scale).moveTo(cx + 3.5 * scale, cy - 3.5 * scale).lineTo(cx - 3.5 * scale, cy + 3.5 * scale).stroke().restore();
  const field = (name, value, x, y, w) => { // "NAME: ______value______" like the printed form
    doc.font('Helvetica-Bold').fontSize(8.5).fillColor(BLACK);
    const lw = doc.widthOfString(name) + 4;
    doc.text(name, x, y, { lineBreak: false });
    doc.save().lineWidth(0.6).strokeColor(BLACK).moveTo(x + lw, y + 10.5).lineTo(x + w, y + 10.5).stroke().restore();
    doc.font('Helvetica-Bold').fontSize(9).text(String(value ?? ''), x + lw, y + 0.5, { width: w - lw, height: 10, align: 'center', ellipsis: true });
    return x + w + 10;
  };

  const drawPage = (reg, start, pageNo, pageTotal, ROW, perPage) => {
    doc.addPage({ size: 'A4', layout: 'landscape', margin: 0 });
    doc.font('Helvetica-Bold').fontSize(11).fillColor(BLACK).text(sh.classCode, L, 18, { lineBreak: false });
    doc.font('Helvetica').fontSize(9).text(FORM_NO, R - 140, 20, { width: 140, align: 'right', lineBreak: false });
    if (fs.existsSync(LOGO_PATH)) doc.image(LOGO_PATH, L, 33, { width: 66 });
    doc.font('Helvetica-Bold').fontSize(14).text('MUKIRIA TECHNICAL TRAINING INSTITUTE', 0, 32, { width: PW, align: 'center', lineBreak: false });
    doc.fontSize(11).text('STUDENTS ATTENDANCE REGISTER', 0, 50, { width: PW, align: 'center', lineBreak: false });
    let x = 100;
    x = field('WEEK:', sh.weekNumber ?? '', x, 70, 62);
    x = field('DATE FROM:', sh.dateFrom, x, 70, 108);
    x = field('TO:', sh.dateTo, x, 70, 74);
    x = field('CLASS:', sh.classCode, x, 70, 150);
    x = field('DEPARTMENT:', sh.department, x, 70, 205);
    field('YEAR:', sh.year, x, 70, 66);
    x = 100;
    x = field('CLASS TEACHER :', sh.classTeacher, x, 88, 280);
    const allSubjects = [...new Set(sh.subjects.map((subject) => subject.unit).filter(Boolean))].join(' / ');
    field('SUBJECT :', allSubjects, x, 88, 405);

    const y0 = tableTop, yIn = y0 + hDay + hTime, yOut = yIn + hIn, ySubject = yOut + hOut, yLab = ySubject + hSubject, yBody = y0 + headH;
    box(L, y0, wSN, headH); label('S/N\nO', L, y0, wSN, headH, { size: 7, bold: true });
    box(xADM, y0, wADM + wNAME, hDay + hTime); label('DETAILS', xADM, y0, wADM + wNAME, hDay + hTime, { size: 9, bold: true });
    box(xADM, yIn, wADM + wNAME, hIn); label('TIME IN', xADM, yIn, wADM + wNAME, hIn, { size: 8, bold: true });
    box(xADM, yOut, wADM + wNAME, hOut); label('TIME OUT', xADM, yOut, wADM + wNAME, hOut, { size: 8, bold: true });
    box(xADM, ySubject, wADM + wNAME, hSubject); label('SUBJECT', xADM, ySubject, wADM + wNAME, hSubject, { size: 8, bold: true });
    box(xADM, yLab, wADM, hLab); label('ADM NO', xADM, yLab, wADM, hLab, { size: 7.5, bold: true });
    box(xNAME, yLab, wNAME, hLab); label('NAME', xNAME, yLab, wNAME, hLab, { size: 9, bold: true });
    const cellOf = new Map(reg.cells.map((c) => [c.day * 4 + c.slot, c]));
    for (let d = 0; d < 5; d++) {
      box(xS + d * 4 * slotW, y0, 4 * slotW, hDay); label(DAY_NAMES[d], xS + d * 4 * slotW, y0, 4 * slotW, hDay, { size: 8, bold: true });
      for (let k = 0; k < 4; k++) {
        const cx = xS + (d * 4 + k) * slotW, c = cellOf.get(d * 4 + k);
        box(cx, y0 + hDay, slotW, hTime); label(SLOTS[k].label.join('\n'), cx, y0 + hDay, slotW, hTime, { size: 5.5 });
        box(cx, yIn, slotW, hIn); if (c) label(c.timeIn, cx, yIn, slotW, hIn, { size: 5 });
        box(cx, yOut, slotW, hOut); if (c?.timeOut) label(c.timeOut, cx, yOut, slotW, hOut, { size: 5 });
        box(cx, ySubject, slotW, hSubject);
        const units = sh.subjectsBySlot.find((entry) => entry.slot === d * 4 + k)?.units;
        if (units) label(units, cx, ySubject, slotW, hSubject, { size: 5, bold: true });
        box(cx, yLab, slotW, hLab);
      }
    }

    const rows = reg.rows.slice(start, start + perPage);
    const rowTextSize = Math.max(3, Math.min(7, ROW * 0.9));
    const markScale = Math.min(1, ROW / 12);
    rows.forEach((r, i) => {
      const y = yBody + i * ROW;
      box(L, y, wSN, ROW); label(start + i + 1, L, y, wSN, ROW, { size: rowTextSize });
      box(xADM, y, wADM, ROW); label(r.adm, xADM, y, wADM, ROW, { size: rowTextSize, align: 'left' });
      box(xNAME, y, wNAME, ROW); label(String(r.name).toUpperCase(), xNAME, y, wNAME, ROW, { size: rowTextSize, align: 'left' });
      r.marks.forEach((m, j) => { const cx = xS + j * slotW; box(cx, y, slotW, ROW); if (m === 'P') tick(cx + slotW / 2, y + ROW / 2, markScale); else if (m === 'A') cross(cx + slotW / 2, y + ROW / 2, markScale); });
    });
    const y = yBody + rows.length * ROW;
    if (!reg.rows.length) label('No students in this class.', xADM, y + 2, 300, 14, { size: 8, align: 'left' });
    if (start + perPage >= reg.rows.length) { // signature row + HOD comments
      box(L, y, wSN, hFoot); box(xADM, y, wADM + wNAME, hFoot); label("TEACHER'S SIGN", xADM, y, wADM + wNAME, hFoot, { size: 8, bold: true, align: 'left' });
      for (let j = 0; j < 20; j++) { const cx = xS + j * slotW; box(cx, y, slotW, hFoot); if (cellOf.get(j)?.signed) label('signed', cx, y, slotW, hFoot, { size: 5, color: '#666666' }); }
      doc.font('Helvetica-Bold').fontSize(9).fillColor(BLACK).text("H.O.D'S COMMENTS:", L + 30, y + hFoot + 16, { lineBreak: false });
      doc.save().lineWidth(0.6).strokeColor(BLACK).moveTo(L + 135, y + hFoot + 26).lineTo(L + 560, y + hFoot + 26).stroke().restore();
    }
    const notes = [`Generated ${generatedAt(new Date())} by MTTI Smart Campus`];
    if (pageTotal > 1) notes.push(`page ${pageNo} of ${pageTotal}`);
    if (sh.weekendSkipped) notes.push(`${sh.weekendSkipped} Saturday/Sunday lesson(s) not shown`);
    doc.font('Helvetica').fontSize(6).fillColor('#777777').text(notes.join('  ·  '), L, PH - 16, { lineBreak: false });
  };

  const reg = { unit: '', lecturer: '', cells: sh.classRegister.cells, rows: sh.classRegister.rows };
  const n = reg.rows.length;
  const ROW = n ? Math.min(17, availRows / n) : 17;
  const perPage = Math.max(1, n);
  drawPage(reg, 0, 1, 1, ROW, perPage);
  doc.end();
}

function sendWeeklyCsv(res, sh, filename) {
  const headers = ['Adm No', 'Name', ...sh.sessions.map((s) => `S${s.n} ${s.label} ${s.unit}`), 'Present', 'Late', 'Absent', 'Week %'];
  const rows = sh.students.map((s) => [s.adm, s.name, ...s.marks, s.present, s.late, s.absent, `${s.pct}%`]);
  sendCsv(res, filename, headers, rows);
}

async function sendWeekly(req, res, cc) {
  const format = String(req.query.format || 'json').toLowerCase();
  if (!['json', 'pdf', 'csv'].includes(format)) return bad(res, 'format must be json, pdf or csv.');
  const sh = await buildWeeklySheet(cc, req.query.week ? String(req.query.week) : '');
  if (!sh) return bad(res, 'week must be a date like 2026-10-09 (any day in the week you want).');
  const base = `weekly-attendance-${cc.replace(/\W+/g, '_')}-${sh.weekStart}`;
  if (format === 'pdf') return sendRegisterPdf(res, sh, `${base}.pdf`);
  if (format === 'csv') return sendWeeklyCsv(res, sh, `${base}.csv`);
  res.json(sh);
}

// class rep: always their own class (admin may pass ?class_code=)
export const weeklySheetRep = wrap(async (req, res) => {
  const cc = classOf(req);
  if (!cc) return bad(res, 'Your account has no class assigned.');
  return sendWeekly(req, res, cc);
});
// HOD / admin: any class, chosen with ?class_code=
export const weeklySheetHod = wrap(async (req, res) => {
  const cc = String(req.query.class_code || '');
  if (!cc) return bad(res, 'class_code is required.');
  if (!(await one('SELECT class_code FROM classes WHERE class_code = ?', [cc]))) return bad(res, 'Class not found.', 404);
  return sendWeekly(req, res, cc);
});

// =========================================================================================
// NOTIFICATIONS (the bell in the top bar). Computed from live data on request, so there is nothing to store or clean up.
// Ids are stable while the situation is unchanged (and change when it does, e.g. "3 waiting" -> "4 waiting"), which is
// how the app knows what is new. "Read" state lives in the user's own browser.
// =========================================================================================
const daysAgo = (n) => new Date(Date.now() - n * 86400000);
const KIND_ORDER = { warn: 0, ok: 1, info: 2 };

export const notifications = wrap(async (req, res) => {
  const role = req.user.role, items = [];
  const add = (id, kind, icon, title, text, link, when) => items.push({ id, kind, icon, title, text, link, when: when ? `${fmtDate(when)} ${fmtTime(when)}` : null });
  const count = async (sql, params = []) => (await one(sql, params)).n;
  const weekend = (() => { const d = new Date().getDay(); return d === 5 || d === 6 || d === 0; })(); // Friday to Sunday

  if (role === 'student' || role === 'student_rep') {
    const st = await me(req);
    if (st) {
      const live = await one('SELECT id, unit_name FROM sessions WHERE class_code = ? AND is_active = 1 ORDER BY id DESC LIMIT 1', [st.class_code]);
      if (live && !(await one('SELECT id FROM attendance_logs WHERE session_id = ? AND adm_no = ?', [live.id, st.adm_no]))) add(`open-${live.id}`, 'warn', '📷', `Attendance is open: ${live.unit_name}`, 'Scan the class QR code to check in.', '/scan');
      const pct = Number(st.attendance_pct);
      if ((await sessionsHeld(st.class_code)) > 0 && pct < T) add(`low-${Math.floor(pct)}`, 'warn', '⚠️', `Your attendance is ${pct.toFixed(1)}%`, `You need at least ${T}% to sit exams.`, '/student/exam-eligibility');
      for (const a of await q('SELECT id, message, created_at FROM chat_messages WHERE class_code = ? AND is_announcement = 1 AND created_at >= ? ORDER BY id DESC LIMIT 5', [st.class_code, sqlDate(daysAgo(7))])) add(`ann-${a.id}`, 'info', '📢', 'Class announcement', a.message, '/student/chat', a.created_at);
      for (const t of await q("SELECT id, status, created_at FROM temp_id_requests WHERE adm_no = ? AND status IN ('approved', 'rejected') AND created_at >= ? ORDER BY id DESC LIMIT 3", [st.adm_no, sqlDate(daysAgo(7))])) add(`tid-${t.id}-${t.status}`, t.status === 'approved' ? 'ok' : 'warn', '🪪', `Your temporary ID was ${t.status}`, t.status === 'approved' ? 'It is valid for 24 hours.' : 'Ask your class rep if you still need one.', '/student/request-temp-id', t.created_at);
      if (role === 'student_rep') {
        const waiting = await count("SELECT COUNT(*) AS n FROM temp_id_requests t JOIN students s ON s.adm_no = t.adm_no JOIN users u ON u.id = s.user_id WHERE u.class_code = ? AND t.status = 'pending'", [st.class_code]);
        if (waiting) add(`rep-tid-${waiting}`, 'warn', '🪪', `${waiting} temporary ID request${waiting > 1 ? 's' : ''} waiting`, 'Students in your class are waiting for you to approve.', '/rep/temp-ids');
        const tt = await one("SELECT id, status, term, hod_comment FROM timetable_versions WHERE class_code = ? AND status IN ('approved', 'rejected') AND created_at >= ? ORDER BY id DESC LIMIT 1", [st.class_code, sqlDate(daysAgo(14))]);
        if (tt) add(`tt-${tt.id}-${tt.status}`, tt.status === 'approved' ? 'ok' : 'warn', '🗓️', `Your timetable was ${tt.status}`, tt.status === 'rejected' && tt.hod_comment ? `HOD: ${tt.hod_comment}` : tt.term, '/rep/timetable');
        if (weekend) add(`weekly-${isoDay(weekBounds('').mon)}`, 'info', '🖨️', "Print this week's attendance register", 'Download it, print it, and get it signed.', '/rep/weekly-sheet');
      }
    }
  } else if (role === 'teacher') {
    const waiting = (await lecturerSessions(req)).filter((s) => !s.signed_at && !s.is_active).length;
    if (waiting) add(`sign-${waiting}`, 'warn', '✍️', `${waiting} lesson${waiting > 1 ? 's' : ''} waiting for your signature`, 'Confirm the class register for each lesson.', '/teacher/sign-attendance');
  } else if (role === 'hod' || role === 'admin') {
    if (role === 'hod') {
      const reps = await count("SELECT COUNT(*) AS n FROM users WHERE role = 'student_rep' AND status = 'pending'");
      if (reps) add(`reps-${reps}`, 'warn', '✅', `${reps} class rep${reps > 1 ? 's' : ''} awaiting approval`, 'They cannot sign in until you approve them.', '/hod/approve-rep');
      const tts = await count("SELECT COUNT(*) AS n FROM timetable_versions WHERE status = 'pending'");
      if (tts) add(`tts-${tts}`, 'warn', '🗓️', `${tts} timetable${tts > 1 ? 's' : ''} awaiting approval`, 'Open the file and approve or reject it.', '/hod/timetables');
      const risk = (await allStudentsWithStats()).filter((s) => s.attendance < T).length;
      if (risk) add(`risk-${risk}`, 'info', '⚠️', `${risk} student${risk > 1 ? 's' : ''} below ${T}% attendance`, 'They are at risk of being barred from exams.', '/hod/at-risk');
    } else {
      const staff = await count("SELECT COUNT(*) AS n FROM users WHERE role IN ('teacher', 'hod', 'admin') AND status = 'pending'");
      if (staff) add(`staff-${staff}`, 'warn', '👥', `${staff} staff registration${staff > 1 ? 's' : ''} awaiting approval`, 'Approve or reject them.', '/admin/staff');
      if (!isEmailConfigured()) add('email-unset', 'warn', '📧', "Email isn't set up", 'Nobody can reset a forgotten password by email until it is.', '/admin/settings');
      if (!(await one("SELECT setting_value FROM app_settings WHERE setting_key = 'term_start'"))) add('term-unset', 'info', '⚙️', 'Term start date not set', 'Printed registers will have a blank WEEK number.', '/admin/settings');
    }
  }
  items.sort((a, b) => KIND_ORDER[a.kind] - KIND_ORDER[b.kind]);
  res.json({ items: items.slice(0, 20) });
});
